create table tax_users (
    id bigint generated by default as identity,
    created_at timestamp,
    npwp varchar(15) not null,
    file varchar(255) not null,
    file_path varchar(255) not null,
    primary key (id)
);

create table trade_confo_users (
    id bigint generated by default as identity,
    created_at timestamp,
    deposito_number varchar(12) not null,
    file varchar(255) not null,
    file_path varchar(255) not null,
    primary key (id)
);

create table trade_loan_users (
    id bigint generated by default as identity,
    created_at timestamp,
    cif varchar(6) not null,
    file varchar(255) not null,
    file_path varchar(255) not null,
    primary key (id)
);

create table api_keys (
    id bigint generated by default as identity,
    created_at timestamp,
    api_key varchar(255) not null,
    description varchar(255) not null,
    unique (api_key),
    primary key (id)
);

INSERT INTO api_keys (created_at, api_key, description)
VALUES
    (NOW(), 'ConfoOqYA18bMMeLnIMOsvvzOIGtucsp5MViMmUHwtgjBo58yXhsKiKlSN4XFAvYK', 'X-API-KEY for users confo'),
    (NOW(), 'LoannbEdkhGs9bx3pfFxmOsdhudGYZVQ0AQ5ELDeOYp2pGg3HpUUQ3WI12zuOBoz', 'X-API-KEY for users loan'),
    (NOW(), 'Taxdmu0X2hMVmqRZLBi4a0DNY9NVWB9cPFach1h3kq0dchtPfZszMzOhmw46o7EP', 'X-API-KEY for users tax');
